name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Get dependencies
      run: go mod download
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Run go fmt check
      run: |
        fmt_files=$(go fmt ./...)
        if [ -n "$fmt_files" ]; then
          echo "The following files need formatting:"
          echo "$fmt_files"
          exit 1
        fi

  build-macos:
    runs-on: macos-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Build macOS binary
      run: |
        GOOS=darwin GOARCH=arm64 go build -o bin/i18n-mcp-darwin-arm64 ./cmd/main.go
        GOOS=darwin GOARCH=amd64 go build -o bin/i18n-mcp-darwin-amd64 ./cmd/main.go
    
    - name: Upload macOS ARM64 artifact
      uses: actions/upload-artifact@v3
      with:
        name: i18n-mcp-darwin-arm64
        path: bin/i18n-mcp-darwin-arm64
    
    - name: Upload macOS AMD64 artifact
      uses: actions/upload-artifact@v3
      with:
        name: i18n-mcp-darwin-amd64
        path: bin/i18n-mcp-darwin-amd64